GT-519-mitigate-jakarta.el-dependency-vulnerability
elimuinformatics/a2d2 pull request #72
Opened 2021-12-03 13:10 UTC by vdeshkar

Done with mitigating jakarta.el dependency for a2d2,
Done with build and test locally

2021-12-03 13:36 UTC, ddjain commented on a2d2-api/pom.xml
> +		<!-- <dependency> <groupId>com.fasterxml.jackson.core</groupId> <artifactId>jackson-databind</artifactId>
@vdeshkar please remove commented code.

2021-12-03 13:36 UTC, ddjain commented on a2d2-api/pom.xml
> +		<!-- <dependency> <groupId>ch.qos.logback</groupId> <artifactId>logback-classic</artifactId>
@vdeshkar please remove commented code.

2021-12-03 13:36 UTC, ddjain commented on a2d2-api/pom.xml
> +		<!-- <dependency> <groupId>com.jayway.jsonpath</groupId> <artifactId>json-path</artifactId>
@vdeshkar please remove commented code.

2021-12-03 13:37 UTC, ddjain requested changes
Remove commented code

2021-12-03 13:47 UTC, ddjain submitted a review, later dismissed

2021-12-04 13:11 UTC, marianbuenosayres submitted a review, later dismissed

2021-12-06 11:34 UTC, darshan-ht approved these changes

2021-12-06 11:48 UTC, darshan-ht approved these changes

2021-12-06 11:51 UTC, ddjain approved these changes

2021-12-06 12:01 UTC, merged